In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mglearn
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import f1_score
import cv2
import csv

In [2]:
product2_image= cv2.imread('./data/product2.jpg')
data = pd.read_csv('./data/bgr.csv', header = None)
height, width, channels = product2_image.shape[:3]

product2_bgr = np.array([])
for i in range(1, 50, 5):
    for j in range(1, 50, 5):
        tmp = np.array(product2_image[i, j, :])
        print(tmp)
        product2_bgr = np.append(product2_bgr, tmp, axis=0)

print(product2_bgr)
    
data = data.values


X_data = data[:,:-1]
y_data = data[:,-1]
X_test = product_bgr[:,:-1]
sum_train = 0
sum_test = 0
max_test = 0

for i in range(50):
    mlp = MLPClassifier(solver = "lbfgs", max_iter = 500, hidden_layer_sizes = [10]).fit(X_data, y_data)
    predict = mlp.predict(X_test)
    predict_sum = sum(predict)
    
print(predict_sum)

predict = mlp.predict(X_test)
predict_sea = predict[0:10]
predict_land = predict[10:]

# print("予測結果 \n sea:{} \n land:{}".format(predict_sea, predict_land))
print("Accuracy on training set: {:.3f}".format(sum_train/50))
print("Accuracy on test set: {:.3f}".format(sum_test/50))
print("Max on training set: {:.3f}".format(max_test))
# print("F1 score: {:.4f}".format(f1_score(y_test, predict)))

[58 55 70]
[105 113 120]
[100 106 117]
[113 113 127]
[119 119 135]
[128 120 127]
[86 73 71]
[111 104 107]
[84 73 76]
[70 56 60]
[103 101 131]
[69 78 91]
[30 42 42]
[68 74 79]
[74 78 79]
[89 82 79]
[97 90 87]
[83 83 83]
[92 93 97]
[84 84 90]
[104 106 117]
[126 132 137]
[ 99  98 108]
[61 55 66]
[72 66 67]
[89 84 83]
[74 80 85]
[66 83 86]
[73 94 92]
[62 88 82]
[77 80 84]
[60 55 56]
[87 88 86]
[72 78 77]
[82 95 93]
[ 84 105 102]
[ 75 100  96]
[40 67 64]
[ 69 100  97]
[118 142 142]
[117 110 115]
[77 87 87]
[ 77 110 103]
[ 70 117 109]
[53 95 88]
[ 74 106 101]
[ 98 120 115]
[145 161 154]
[176 183 186]
[140 127 141]
[60 59 63]
[66 93 89]
[ 57 110 100]
[ 78 122 115]
[59 89 84]
[155 169 167]
[147 153 152]
[77 89 89]
[131 139 139]
[164 158 163]
[ 78 104 104]
[ 56 106  88]
[51 97 78]
[27 53 47]
[177 185 185]
[72 87 89]
[131 127 132]
[171 172 176]
[121 134 132]
[83 78 79]
[26 71 52]
[45 60 52]
[73 89 88]
[71 92 93]
[165 168 172]
[81 97 96]
[139 143 144]
[108 120 126]
[101 107 112]
[147 137 143]
[ 7

NameError: name 'product_bgr' is not defined